live_config_reload = true

[window]
decorations_theme_variant = "Dark" 
title = "btw"
padding.x = 10
padding.y = 10

[keyboard]
bindings = [{ key = "Space", mods = "Control", chars = "\u0000" }]

[colors.primary]
background = "#101317"
foreground = "#d4d4d5"

[colors.normal]
white = "#d4d4d5"
black = "#101317"
red = "#f87070"
green = "#37d99e"
blue = "#7ab0df"
yellow = "#ffe59e"
cyan = "#50cad2"

[font]
normal.family = "JetBrainsMono Nerd Font"
bold.family = "JetBrainsMono Nerd Font"
italic.family = "JetBrainsMono Nerd Font"
bold_italic.family = "JetBrainsMono Nerd Font"
size = 12.0

[cursor]
style = { blinking = "Always" }

[shell]
program = "wsl"
args = [ "~" ]

[window.dimensions]
columns = 140
lines = 50
