return {
  ensure_installed = {
    "bash",
    "c",
    "css",
    "go",
    "gomod",
    "gowork",
    "gosum",
    "html",
    "javascript",
    "json",
    "lua",
    "vue",
    "markdown",
    "yaml",
    "scss",
    "toml",
    "tsx",
    "typescript",
    "vim",
    "vimdoc",
  },
  auto_install = true,
  sync_install = false,
  indent = { enable = true },
  highlight = { enable = true },
  query_linter = {
    enable = true,
    use_virtual_text = true,
    lint_events = { "BufWrite", "CursorHold" },
  },
}
