[general]
live_config_reload = true
import = [
    "./themes/tokyonight.toml"
]

[window]
decorations = "none"
title = "btw"
padding.x = 16
padding.y = 16
opacity = 0.92

[font]
normal.family = "terminal-font"
bold.family = "terminal-font"
italic.family = "terminal-font"
bold_italic.family = "terminal-font"
size = 12.0
offset.y = 6

[cursor]
style = { blinking = "Always" }

