[general]
live_config_reload = true
import = [
    "./themes/tokyonight.toml"
]

[window]
decorations = "none"
title = "btw"
padding.x = 24
padding.y = 24
opacity = 0.90

[font]
normal.family = "terminal-font"
bold.family = "terminal-font"
italic.family = "terminal-font"
bold_italic.family = "terminal-font"
size = 12.0

[cursor]
style = { blinking = "Always" }

